backend:
  name: github
  repo: mrmgee/green1 # Path to your Github repository
  branch: master # Branch to update
  site_domain: mrmgee.github.io/green1/ # Your Netlify site address if different from host
